services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: on-failure
    networks:
      - inception_net
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    restart: on-failure
    networks:
      - inception_net
networks:
  inception_net:
    driver: bridge
volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mofouzi/data/mariadb
secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt